name: CI with Docker

on:
  push

env:
  DOCKER_USERNAME: ${{vars.DOCKERHUBNAME}}  
  DOCKER_PASSWORD: ${{secrets.DOCKERHUBPASS}}
  DOCKER_IMAGE: KG26-26/my-python-deploy-test

jobs:
  build-using-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Docker login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}
          
      - name: Docker Build
        run: |
          docker build -t $DOCKER_IMAGE:${{github.sha}} .
          docker tag $DOCKER_IMAGE:${{github.sha}} $DOCKER_IMAGE:latest
          
      - name: Push the Docker Image to Hub
        run: |
          docker push $DOCKER_IMAGE:${{ github.sha }}
          docker push $DOCKER_IMAGE:latest
