name: Docker

on:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Build and push AUTH service
        run: |
          docker build -t ghcr.io/oussamalakhdar/auth-service:django .
          docker push ghcr.io/oussamalakhdar/auth-service:django

      # - name: push docker image
      #   uses: mr-smithers-excellent/docker-build-push@v6
      #   with:
      #     image: python-app-image
      #     registry: ghcr.io
      #     tags: v1.0
      #     username: ${{ secrets.GHCR_USERNAME }}
      #     password: ${{ secrets.GHCR_PASSWORD }}

      # - name: push docker image
      #   uses: mr-smithers-excellent/docker-build-push@v6
      #   with:
      #     image: auth-service
      #     registry: ghcr.io
      #     dockerfile: ./backend/auth/intranetauth/compose/production/django/
      #     tags: django
      #     username: ${{ secrets.GHCR_USERNAME }}
      #     password: ${{ secrets.GHCR_PASSWORD }}

      # - name: push docker image
      #   uses: mr-smithers-excellent/docker-build-push@v6
      #   with:
      #     image: auth-service
      #     registry: ghcr.io
      #     dockerfile: ./backend/auth/intranetauth/compose/production/postgres/
      #     tags: postgres
      #     username: ${{ secrets.GHCR_USERNAME }}
      #     password: ${{ secrets.GHCR_PASSWORD }}

      # - name: push docker image
      #   uses: mr-smithers-excellent/docker-build-push@v6
      #   with:
      #     image: auth-service
      #     registry: ghcr.io
      #     dockerfile: ./backend/auth/intranetauth/compose/production/traefik/
      #     tags: traefik
      #     username: ${{ secrets.GHCR_USERNAME }}
      #     password: ${{ secrets.GHCR_PASSWORD }}


